SMS/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('adminapp.urls')),

path('facultyapp/', include('facultyapp.urls')),
path('studentapp/', include('studentapp.urls'))
]

facultyapp/urls.py
from django.urls import path,include
from . import views
app_name = 'facultyapp'
urlpatterns = [
    path('projecthomepage/',views.projecthomepage,name='projecthomepage'),
    path('FacultyHomePage/',views.FacultyHomePage,name='FacultyHomePage'),
    path('createpost/', views.create_post_page_call, name='createpost'),
    path('createpostlogic/', views.createpost, name='createpostlogic'),
    path('posts_list/', views.post_list, name='post_list'),  # URL for listing all posts
    path('post_detail/<slug:slug>/', views.post_detail, name='post_detail'),
    path('add_course', views.add_course, name='add_course'),
path('addcoursepagecall', views.add_course_page_call, name='addcoursepagecall'),
    path('viewstudents', views.view_student_list, name='viewstudents'),
path('postmarks', views.post_marks, name='postmarks'),
]

studentapp/urls.py
from django.urls import path,include
from . import views
app_name = 'studentapp'
urlpatterns = [
    path('name/',views.name,name='name'),
    path('StudentHomePage/',views.StudentHomePage,name='StudentHomePage'),
    path('viewmarks/', views.view_marks, name='viewmarks'),
]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=" {% url 'facultyapp:FacultyHomePage' %} ">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'addtaskpagecall' %}">To Do</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
              <li><a class="dropdown-item" href="{% url 'calculatorlogic' %}">Calculator</a></li>
              <li><a class="dropdown-item" href="{% url 'timepagelogic' %}">DateTimePage</a></li>



              <li><a class="dropdown-item" href="{% url 'randomlogic' %}">Random</a></li>


          </ul>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="#">Add Blogs</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">Add Course</a>
        </li>
                    <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:viewstudents' %}">View Student List</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:postmarks' %}">PostMarks</a>
        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}
 </li>
      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'addtaskpagecall' %}">To Do</a></li>
            <li><a class="dropdown-item" href="{% url 'addcontactpagecall' %}">Contact Manager</a></li>
               <li><a class="dropdown-item" href="{% url 'uploadfile' %}">Pie graph generator</a></li>
              <li><a class="dropdown-item" href="{% url 'calculatorlogic' %}">Calculator</a></li>
              <li><a class="dropdown-item" href="{% url 'timepagelogic' %}">DateTimePage</a></li>
              <li><a class="dropdown-item" href="{% url 'feedback' %}">Feedback Form</a></li>



              <li><a class="dropdown-item" href="{% url 'randomlogic' %}">Random</a></li>


          </ul>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student_page_call' %}">Add Student</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'student_list_page_call' %}">View Students</a>
        </li>
      </ul>
    </div>
  </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
</nav>

</body>
{% block body %}
{% endblock %}
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <li><a class="nav-link" href="{% url 'studentapp:viewmarks' %}">View marks</a></li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'studentapp:viewmarks' %}">View marks</a></li>
            <li><a class="dropdown-item" href="{% url 'addtaskpagecall' %}">To Do</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
              <li><a class="dropdown-item" href="{% url 'calculatorlogic' %}">Calculator</a></li>
              <li><a class="dropdown-item" href="{% url 'timepagelogic' %}">DateTimePage</a></li>



              <li><a class="dropdown-item" href="{% url 'randomlogic' %}">Random</a></li>


          </ul>
        </li>
      </ul>
    </div>
  </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="#">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="#">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
</nav>

{% block body %}

{% endblock %}
</body>
</html>